# https-github.com-humanode-network-humanode-issues-new
clone Thread 'tokio-runtime-worker' panicked at 'enroll failed: server error: unknown error: {"errorCode":"UNKNOWN_CALL"}', crates/humanode-peer/src/service.rs:435 This is a bug. Please report it at: https://github.com/humanode-network/humanode/issues/new
